# Generated by Django 4.1.9 on 2023-05-24 23:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('contraseña', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('profesor', djongo.models.fields.JSONField(null=True)),
                ('materia', models.IntegerField()),
                ('aulas', djongo.models.fields.JSONField(null=True)),
                ('horario', djongo.models.fields.JSONField(default={'Horario por asignar': 0})),
            ],
            options={
                'db_table': 'clases',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.IntegerField()),
                ('programa_academico', models.CharField(max_length=40)),
                ('nombre_completo', models.CharField(max_length=70)),
                ('contraseña', models.CharField(max_length=30)),
                ('aprobadas', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('pagado', models.IntegerField(default=0)),
                ('valor', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero_creditos', models.IntegerField()),
                ('prerrequisitos', djongo.models.fields.JSONField(null=True)),
            ],
            options={
                'db_table': 'materias',
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.IntegerField()),
                ('id_clase', models.IntegerField()),
                ('fecha_registro', models.DateField()),
                ('id_factura', models.IntegerField()),
            ],
            options={
                'db_table': 'registros',
            },
        ),
    ]
